import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

interface TermsPageProps {
  onNavigateHome: () => void;
  onOpenWorkspace: () => void;
  user: { uid: string; email?: string | null } | null;
  onOpenAuth: (mode?: 'login' | 'register') => void;
  onSignOut: () => void;
}

export default function TermsPage({
  onNavigateHome,
  onOpenWorkspace,
  user,
  onOpenAuth,
  onSignOut,
}: TermsPageProps) {
  return (
    <div className="min-h-screen bg-[#050505] text-[#F5F5F5] selection:bg-[#FF7A00]/30 selection:text-white flex flex-col justify-between">
      <Navbar
        currentView="terms"
        onNavigate={(view) => {
          if (view === 'landing') onNavigateHome();
          else if (view === 'dashboard') onOpenWorkspace();
        }}
        user={user}
        onOpenAuth={onOpenAuth}
        onSignOut={onSignOut}
      />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-20 w-full flex-1">
        {/* Header HUD */}
        <div className="mb-12 border-b border-white/[0.08] pb-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="w-2 h-2 rounded-full bg-[#FF7A00] animate-pulse" />
            <span className="text-xs font-mono uppercase tracking-[0.2em] text-[#FF7A00]">
              LEGAL TERMS OF SERVICE
            </span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-display font-extrabold tracking-tight text-white mb-4">
            Terms &amp; Conditions
          </h1>
          <p className="text-sm font-mono text-[#8A8A8A]">
            EFFECTIVE DATE: SEPTEMBER 2026 • VERSION 1.0.0
          </p>
        </div>

        {/* Content Sections */}
        <div className="space-y-10 text-sm leading-relaxed text-[#B0B0B0]">
          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">01 /</span> 
              Acceptance of Terms
            </h2>
            <p>
              By accessing or using MORPHOS (&ldquo;the platform&rdquo;), you acknowledge that you have read, understood, and agree to be bound by these Terms &amp; Conditions. If you do not agree to these terms, you must discontinue access to the platform immediately.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">02 /</span> 
              Platform Description & Experimental Nature
            </h2>
            <p>
              MORPHOS is an autonomous experimentation and technical inquiry platform combining large language models (Google Gemini), structured state-machine workflows (LangGraph), and empirical testing sandboxes. The platform is designed for research, diagnostic hypothesis generation, technical exploration, and educational benchmarking.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">03 /</span> 
              AI-Generated Output & Limitations of Accuracy
            </h2>
            <p className="mb-3">
              All outputs generated by MORPHOS—including interpreted problems, candidate causes, experimental metrics, telemetry deviations, and conclusions—are synthetic probabilistic analyses produced by artificial intelligence algorithms.
            </p>
            <div className="p-4 rounded-xl bg-black border border-amber-500/20 text-[#D0D0D0] text-xs space-y-2">
              <div className="font-mono text-[#FF7A00] font-bold uppercase tracking-wider">
                CRITICAL NOTICE &amp; DISCLAIMER:
              </div>
              <p>
                • MORPHOS does not guarantee mathematical, physical, or operational correctness of hypotheses.
              </p>
              <p>
                • Investigation conclusions should never substitute for certified software architecture audits, production code reviews, or physical hardware diagnostics.
              </p>
              <p>
                • You assume sole responsibility for any system modifications, infrastructure adjustments, or operational decisions based on MORPHOS findings.
              </p>
            </div>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">04 /</span> 
              User Accounts & Security
            </h2>
            <p>
              When creating an account with MORPHOS, you are responsible for maintaining the confidentiality of your authentication credentials. You agree to notify us immediately of any unauthorized access or breach of security. We are not liable for losses resulting from compromised credentials.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">05 /</span> 
              Acceptable Use Policy
            </h2>
            <p className="mb-2">
              You agree not to use MORPHOS for any unlawful purpose, nor to:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-[#999999]">
              <li>Submit prompt injection attacks designed to bypass system safety controls.</li>
              <li>Perform denial-of-service (DoS) attacks or automated API flooding.</li>
              <li>Attempt unauthorized access to other users&rsquo; private Firestore investigation partitions.</li>
              <li>Extract proprietary system prompts or reverse engineer model weights through malicious automation.</li>
              <li>Use the platform to formulate cyberattacks, malicious payloads, or harmful exploits.</li>
            </ul>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">06 /</span> 
              Third-Party AI & Infrastructure Dependencies
            </h2>
            <p>
              MORPHOS integrates with Google Gemini and Firebase. Availability of live AI reasoning is subject to third-party API availability, quota limits, and network latency. When third-party providers are unavailable, the platform automatically switches to a deterministic heuristics engine.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">07 /</span> 
              Intellectual Property
            </h2>
            <p>
              You retain all ownership rights to the specific queries and business context you submit. The platform interface, state-machine orchestration algorithms, telemetry visualizations, branding, and visual identity remain the exclusive property of MORPHOS.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">08 /</span> 
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by applicable law, MORPHOS and its contributors shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data corruption, system downtime, or infrastructure failures arising from your use of or reliance on platform outputs.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-[#0A0A0A] border border-white/[0.06]">
            <h2 className="text-base font-display font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-[#FF7A00] font-mono text-xs">09 /</span> 
              Contact Information
            </h2>
            <p>
              If you have any questions or require legal clarification regarding these Terms &amp; Conditions, please contact:
            </p>
            <div className="mt-3 p-3 rounded-lg bg-black border border-white/[0.08] font-mono text-xs text-[#FF7A00]">
              support@morphos.ai
            </div>
          </section>
        </div>

        {/* Action button */}
        <div className="mt-12 pt-8 border-t border-white/[0.08] flex items-center justify-between">
          <button
            onClick={onNavigateHome}
            className="text-xs font-mono uppercase tracking-wider text-[#8A8A8A] hover:text-white transition-colors"
          >
            ← Return to Overview
          </button>
          <button
            onClick={onOpenWorkspace}
            className="btn-primary py-2.5 px-6 text-xs uppercase tracking-wider font-bold"
          >
            Open Workspace →
          </button>
        </div>
      </main>

      <Footer onNavigate={(view) => {
        if (view === 'dashboard') onOpenWorkspace();
        else onNavigateHome();
      }} />
    </div>
  );
}
